# Generated by Django 4.2.3 on 2023-07-09 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_prodcuto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodcuto',
            name='disponibilidad',
            field=models.BooleanField(null=True),
        ),
    ]
