# Generated by Django 4.2.3 on 2023-07-09 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_prodcuto_disponibilidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodcuto',
            name='disponibilidad',
            field=models.BooleanField(null=True, verbose_name='stock'),
        ),
    ]
