# Generated by Django 4.2.3 on 2023-07-11 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_prodcuto_disponibilidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('es_administrador', models.BooleanField(default=False)),
                ('rut', models.CharField(max_length=12)),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('contrasena', models.CharField(max_length=50)),
                ('imagen', models.ImageField(null=True, upload_to='usuarios')),
                ('suscripcion', models.BooleanField(default=False)),
            ],
        ),
    ]
