# Generated by Django 4.2.3 on 2023-07-11 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_usuario'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuario',
            new_name='Usuario1',
        ),
    ]
