# Generated by Django 4.2.3 on 2023-07-11 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_usuario_usuario1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('es_administrador', models.BooleanField(default=False)),
                ('rut', models.CharField(max_length=12)),
                ('nombres', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254)),
                ('direcion', models.CharField(max_length=50)),
                ('contrasena', models.CharField(max_length=50, verbose_name='contraseña')),
                ('imagen', models.ImageField(null=True, upload_to='usuarios')),
                ('suscripcion', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Usuario1',
        ),
    ]
