# Generated by Django 4.2.3 on 2023-07-11 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_usuario_delete_usuario1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_administrador', models.BooleanField(default=False, null=True)),
                ('rut', models.CharField(max_length=12, null=True)),
                ('nombre', models.CharField(max_length=50, null=True)),
                ('apellido', models.CharField(max_length=50, null=True)),
                ('correo', models.EmailField(max_length=254, null=True)),
                ('direcion', models.CharField(max_length=50, null=True)),
                ('contrasena', models.CharField(max_length=50, null=True, verbose_name='contraseña')),
                ('imagen', models.ImageField(null=True, upload_to='usuarios')),
                ('suscripcion', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
