# Generated by Django 4.2.3 on 2023-07-11 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_ropa'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuario1',
            new_name='Usuario',
        ),
    ]
