# Generated by Django 4.2.3 on 2023-07-11 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_usuario1_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=100)),
                ('precio_unitario', models.IntegerField(verbose_name='precio unitario')),
                ('porc_descto_subscriptor', models.IntegerField(verbose_name='% descuento subscriptor')),
                ('porc_descto_oferta', models.IntegerField(verbose_name='% descuento oferta')),
                ('porc_descto_total', models.IntegerField(verbose_name='% descuento total')),
                ('descto_total', models.IntegerField(verbose_name='descuento total')),
                ('valor_final', models.IntegerField(verbose_name='valor final')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.prodcuto')),
            ],
        ),
        migrations.DeleteModel(
            name='Ropa',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='direcion',
        ),
        migrations.AddField(
            model_name='usuario',
            name='direccion',
            field=models.CharField(max_length=50, null=True, verbose_name='dirección'),
        ),
    ]
